name: mccay
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - pyyaml
  - jq
  - pip
  - pip:
      - openai
      - anthropic
      - feedparser
      - dill
      - strip-ansi
      - PyPDF2
      - pytest
