name: Run tests

on:
  push:
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/python-tests.yml'
  pull_request:
    paths:
      - '**.py'
      - 'tests/**'
      - '.github/workflows/python-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils tesseract-ocr
          python -m pip install --upgrade pip
          pip install openai anthropic feedparser dill strip-ansi \
            pandas numpy pyyaml PyPDF2 fpdf2 pytest
      - name: Run tests
        run: pytest -q
